"""
Django settings for shoonya_backend project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from decouple import config, Csv
from pygments.styles import default

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

SECRET_KEY_RESET_PASSWORD = config("SECRET_KEY_RESET_PASSWORD")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv(), default=[])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "drf_yasg",
    "rest_framework",
    "djoser",
    "users",
    "organizations",
    "workspaces",
    "dataset",
    "projects",
    "tasks",
    "functions",
    "loging",
    "notifications",
    "corsheaders",
    "import_export",
    "django_celery_results",
    "django_celery_beat",
    "django.contrib.postgres",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

CSRF_COOKIE_SECURE = False

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

ROOT_URLCONF = "shoonya_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "shoonya_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
# STATIC_URL = "/static/"
# STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "shoonya_backend.pagination.CustomPagination",
}


# Email Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT")
EMAIL_HOST_USER = config("SMTP_USERNAME")
EMAIL_HOST_PASSWORD = config("SMTP_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

DOMAIN = config("DOMAIN")
SITE_NAME = config("SITE_NAME")

DJOSER = {
    "PASSWORD_RESET_CONFIRM_URL": "#/forget-password/confirm/{uid}/{token}",
    "USERNAME_RESET_CONFIRM_URL": "users/auth/users/username/reset/confirm/{uid}/{token}",
    "ACTIVATION_URL": "users/auth/users/activation/{uid}/{token}",
    "SEND_ACTIVATION_EMAIL": True,
    "SERIALIZERS": {},
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("JWT",),
    "BLACKLIST_AFTER_ROTATION": False,
    "REFRESH_TOKEN_LIFETIME": timedelta(days=20),
    "ACCESS_TOKEN_LIFETIME": timedelta(days=100),
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 102400  # higher than the count of fields

# Logging Configuration

# # Get loglevel from env
LOGLEVEL = config("LOG_LEVEL", default="INFO")

# Define the list of formatters
formatters = {
    "console": {
        "()": "shoonya_backend.logger.ConsoleFormatter",
        "format": "({server_time}) {console_msg}",
        "style": "{",
    },
    "file": {
        "()": "shoonya_backend.logger.FileFormatter",
        "format": "{levelname} ({asctime}) [{module}:{process}|{thread}] {message} [User: {user_email} | Path: {request_path}]",
        "style": "{",
    },
    "csvfile": {
        "format": "{levelname},{asctime},{module},{process},{thread},{message}",
        "style": "{",
    },
}

# Define the list of handlers
handlers = {
    "console": {
        "level": LOGLEVEL,
        "class": "logging.StreamHandler",
        "formatter": "console",
    }
}

# If logging is enabled, add file handlers
if config("LOGGING", default=False, cast=bool):
    # Make a new directory for logs
    Path("/logs/logs_web").mkdir(exist_ok=True)
    handlers["file"] = {
        "level": "WARNING",
        "class": "logging.FileHandler",
        "filename": "/logs/logs_web/default.log",
        "formatter": "file",
    }

    handlers["csvfile"] = {
        "level": "WARNING",
        "class": "logging.FileHandler",
        "filename": "/logs/logs_web/logs.csv",
        "formatter": "csvfile",
    }

#    handlers["logstash"] = {
#        "level": "WARNING",
#        "class": "logstash_formatter.LogstashFormatterTCP",
#        "port": 9600,
#        "version": 1,
#    }

# Setup the Cloud Logging Client
# if os.getenv("GOOGLE_APPLICATION_CREDENTIALS"):
#    client = gc_logging.Client()
#    client.setup_logging(log_level=logging.WARNING)
#    handlers["gcloud-logging"] = {
#        "class": "google.cloud.logging.handlers.CloudLoggingHandler",
#        "client": client,
#    }

# Define logger configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": formatters,
    "handlers": handlers,
    "loggers": {
        "": {
            "level": LOGLEVEL,
            "handlers": handlers.keys(),
        },
        "django": {
            "handlers": [],
        },
        "django.server": {"propagate": True},
    },
}
CELERY_IMPORTS = ("users.tasks", "shoonya_backend.tasks")

# Celery settings
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


# Project lock TTL for task pulling(in seconds)
PROJECT_LOCK_TTL = 5
PROJECT_LOCK_RETRY_INTERVAL = 1

AZURE_STORAGE_CONNECTION_STRING = config("AZURE_STORAGE_CONNECTION_STRING", default='')
TRANSLITERATION_CONTAINER_NAME = config("TRANSLITERATION_CONTAINER_NAME", default='')

# Azure connections
AZURE_CONNECTION_STRING = config("AZURE_CONNECTION_STRING", default='')
STORAGE_ACCOUNT_CONNECTION_STRING = config("STORAGE_ACCOUNT_CONNECTION_STRING", default='')
STORAGE_ACCOUNT_PROFILE_IMAGE_CONTAINER_NAME = config("STORAGE_ACCOUNT_PROFILE_IMAGE_CONTAINER_NAME", default='')
LOGS_CONTAINER_NAME = config("LOGS_CONTAINER_NAME", default='')
CONTAINER_NAME = config("CONTAINER_NAME", default='')
CONTAINER_NAME_FOR_DOWNLOAD_ALL_PROJECTS = config("CONTAINER_NAME_FOR_DOWNLOAD_ALL_PROJECTS", default='')

# Azure Translator
AZURE_TRANSLATOR_TEXT_SUBSCRIPTION_KEY = config("AZURE_TRANSLATOR_TEXT_SUBSCRIPTION_KEY", default='')
AZURE_TRANSLATOR_TEXT_REGION = config("AZURE_TRANSLATOR_TEXT_REGION", default='')
AZURE_TRANSLATOR_TEXT_ENDPOINT = config("AZURE_TRANSLATOR_TEXT_ENDPOINT", default='https://api.cognitive.microsofttranslator.com')

# Indic Trans APIs
INDIC_TRANS_NMT_API = config("INDIC_TRANS_NMT_API", default='')
INDIC_TRANS_V2_URL = config("INDIC_TRANS_V2_URL", default='')
INDIC_TRANS_V2_KEY = config("INDIC_TRANS_V2_KEY", default='')

# Google
GOOGLE_APPLICATION_CREDENTIALS = config("GOOGLE_APPLICATION_CREDENTIALS", default='{}')

# ASR Dhruva
ASR_DHRUVA_URL = config("ASR_DHRUVA_URL", default='')
ASR_DHRUVA_AUTHORIZATION = config("ASR_DHRUVA_AUTHORIZATION", default='')

# Celery Flower
FLOWER_ADDRESS = config("FLOWER_ADDRESS", default='')
FLOWER_PORT = config("FLOWER_PORT", default=5555, cast=int)
FLOWER_USERNAME = config("FLOWER_USERNAME", default='')
FLOWER_PASSWORD = config("FLOWER_PASSWORD", default='')

# MinIO
MINIO_ENDPOINT = config("MINIO_ENDPOINT", default='')
MINIO_ACCESS_KEY = config("MINIO_ACCESS_KEY", default='')
MINIO_SECRET_KEY = config("MINIO_SECRET_KEY", default='')

# Elasticsearch
ELASTICSEARCH_URL = config("ELASTICSEARCH_URL", default='')
INDEX_NAME = config("INDEX_NAME", default='')

# Misc
FRONTEND_URL_FOR_RESET_PASSWORD = config("FRONTEND_URL_FOR_RESET_PASSWORD", default='')
DEFAULT_CELERY_LOCK_TIMEOUT = config("DEFAULT_CELERY_LOCK_TIMEOUT", default=0, cast=int)
BASE_URL = config("BASE_URL", default='')
INDIC_ROMANISED_LOGS = config("INDIC_ROMANISED_LOGS", default='')
API_URL = config("API_URL", default='')
REDIS_HOST = config("REDIS_HOST", default='')
REDIS_PORT = config("REDIS_PORT", default=6379, cast=int)


