# Generated by Django 3.2.16 on 2023-01-27 12:21


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0033_delete_tasklock"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="annotation_status",
            field=models.CharField(
                choices=[
                    ("unlabeled", "unlabeled"),
                    ("labeled", "labeled"),
                    ("skipped", "skipped"),
                    ("draft", "draft"),
                    ("unreviewed", "unreviewed"),
                    ("accepted", "accepted"),
                    ("accepted_with_minor_changes", "accepted_with_minor_changes"),
                    ("accepted_with_major_changes", "accepted_with_major_changes"),
                    ("to_be_revised", "to_be_revised"),
                ],
                default="unlabeled",
                max_length=100,
                verbose_name="annotation_status",
            ),
        ),
    ]
